### ISSUE TITLE
Documenting patches and requirements

### ISSUE THREAD

**Issue by trombik** [iij/ipgen#51]
The `patch` directory contains patches. However, `README.md` does not mention them at all.

Also, `device netmap` is included in `GENERIC` on 14.x.

**Comment by ozaki-r** [comment]
We've updated `README.md`. It should solve the issues.

**Comment by trombik** [comment]
fixed in https://github.com/iij/ipgen/commit/09856f6556ffe1cc3796d790d958e9a7dbd1ed7c
