### ISSUE TITLE
Makefile does not honor DESTDIR

### ISSUE THREAD

**Issue by trombik** [iij/ipgen#52]
The `GNUmakefile`s should use `$DESTDIR` with `$PREFIX`. This can be fixed by #39.

**Comment by trombik** [comment]
The owner of the PR, #39, does not respond. Would you merge a PR if I propose a fix just for ${DESTDIR} part?

**Comment by ozaki-r** [comment]
We're sorry for long delay. We've finally merged the PR.

**Comment by trombik** [comment]
Thanks.
